----------------------------
-- AstroNvim Key Mappings --
----------------------------

return {
  n = {
    [";"] = { ":", desc = "Swap ; for :" },
    [":"] = { ";", desc = "Swap : for ;" },
    ["<leader>ev"] = { ":vsplit ~/.config/nvim/lua/user/init.lua<CR>", silent = true, desc = "Edit config shortcut." },
    ["<leader>cd"] = {
      ":lcd %:h<CR>",
      desc = "Change the cwd to the location of the current buffer, but only for the current buffer.",
    },
    ["<leader><UP>"] = { ":resize +5<CR>", silent = true, desc = "Increase vertical window size." },
    ["<leader><DOWN>"] = { ":resize -5<CR>", silent = true, desc = "Decrease vertical window size." },
    ["<leader><RIGHT>"] = { ":vertical resize +5<CR>", silent = true, desc = "Increase window width." },
    ["<leader><LEFT>"] = { ":vertical resize -5<CR>", silent = true, desc = "Decrease window width." },
    ["<leader>h"] = { ":wincmd h<CR>", desc = "Move focus to window on the left." },
    ["<leader>j"] = { ":wincmd j<CR>", desc = "Move focus to window below" },
    ["<leader>l"] = { ":wincmd l<CR>", desc = "Move focus to window on the right." },
    ["<leader>k"] = { ":wincmd k<CR>", desc = "Move focus to window above." },
    ["<leader>bn"] = { "<cmd>enew<CR>", desc = "New buffer." },
    ["<leader>n"] = { ":bn<CR>", desc = "Show the next buffer." },
    ["<leader>p"] = { ":bp<CR>", desc = "Show the previous buffer." },
    ["<leader>zbb"] = {
      "<cmd> lua buf_kill(0, true)<CR>",
      silent = true,
      desc = "Force delete the buffer, but leave the window open.",
    },
    ["<c-j>"] = { ":m .+1<CR>==", silent = true, desc = "Bubble line down" },
    ["<c-k>"] = { ":m .-2<CR>==", silent = true, desc = "Bubble line up" },
    ["<leader><CR>"] = { ":noh<CR><ESC>", silent = true, desc = "Remove search highlighting" },
    ["<leader>tN"] = { ":tabnew<CR>", desc = "Open new tab." },
    ["<leader>tc"] = { ":tabclose<CR>", desc = "Close tab." },
    ["<leader>tn"] = { ":tabnext<CR>", desc = "Move focus to next tab." },
    ["<leader>tp"] = { ":tabprevious<CR>", desc = "Move focus to previous tab." },
    ["<leader>1"] = { "1gt", desc = "Go to tab number 1." },
    ["<leader>2"] = { "2gt", desc = "Go to tab number 2." },
    ["<leader>3"] = { "3gt", desc = "Go to tab number 3." },
    ["<leader>4"] = { "4gt", desc = "Go to tab number 4." },
    ["<leader>5"] = { "5gt", desc = "Go to tab number 5." },
    ["<leader>6"] = { "6gt", desc = "Go to tab number 6." },
    ["<leader>7"] = { "7gt", desc = "Go to tab number 7." },
    ["<leader>8"] = { "8gt", desc = "Go to tab number 8." },
    ["<leader>9"] = { "9gt", desc = "Go to tab number 9." },
  },
  i = {
    ["<C-j>"] = { "DOWN", desc = "Move down in insert mode." },
    ["<C-l>"] = { "RIGHT", desc = "Move right in insert mode." },
    ["<C-k>"] = { "UP", desc = "Move up in insert mode." },
    ["<C-h>"] = { "LEFT", desc = "Move left in insert mode." },
    ["<C-U>"] = { "<ESC>ui", desc = "From insert mode, exit to normal, undo, reenter insert mode." },
  },
  c = {
    ["<C-h>"] = { "<LEFT>", desc = "Move left in command mode." },
    ["<C-j>"] = { "DOWN", desc = "Move down in command mode." },
    ["<C-l>"] = { "RIGHT", desc = "Move right in command mode." },
    ["<C-k>"] = { "UP", desc = "Move up in command mode." },
  },
  v = {
    ["<c-j>"] = { ":m '>+1<CR>==gv=gv", silent = true, desc = "Bubble line down" },
    ["<c-k>"] = { ":m '<-2<CR>==gv=gv", silent = true, desc = "Bubble line up" },
    ["y"] = { "ygv<ESC>", desc = "Yank and put cursor back." },
  },
}
